version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    #volumes:
    # - './services/users:/usr/src/app'
    expose:
      - 5000
#    ports:
#      - 5001:5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
#      - FLASK_APP=project/__init__.py
#      - FLASK_ENV=development
#      - APP_SETTINGS=project.config.DevelopmentConfig
#      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev  # nuevo
#      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test  # nuevo
    depends_on:  # new
      - users-db

  users-db:  # new
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
#    ports:
#      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
